from src.config import (
    AZURE_FORM_RECOGNIZER_ENDPOINT,
    AZURE_FORM_RECOGNIZER_KEY,
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_KEY,
    AZURE_OPENAI_DEPLOYMENT,
    AZURE_OPENAI_API_VERSION,
    REPO_DOCS_DIR,
)

print("FORM RECOGNIZER ENDPOINT:", AZURE_FORM_RECOGNIZER_ENDPOINT)
print("FORM RECOGNIZER KEY:", "OK" if AZURE_FORM_RECOGNIZER_KEY else "MISSING")
print("OPENAI ENDPOINT:", AZURE_OPENAI_ENDPOINT)
print("OPENAI KEY:", "OK" if AZURE_OPENAI_KEY else "MISSING")
print("DEPLOYMENT:", AZURE_OPENAI_DEPLOYMENT)
print("API VERSION:", AZURE_OPENAI_API_VERSION)
print("REPO_DOCS_DIR:", REPO_DOCS_DIR)